### ISSUE TITLE
Can not build.....

### ISSUE THREAD

**Issue by Gimmo** [Surviver/QuadTree-node.js-addon#1]
**with node-build.cmd:**
```
......... ........, 
In file included from ../collision_filter.h:4:0,
                 from ../collision_filter.cc:1:
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h: In instantiation of 'static T* node::ObjectWr
ap::Unwrap(v8::Local<v8::Object>) [with T = quad_tree::CollisionFilter]':
../collision_filter.cc:108:78:   required from here
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h:34:32: error: 'node::ObjectWrap' is an inacces
sible base of 'quad_tree::CollisionFilter'
     return static_cast<T*>(wrap);
                                ^
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h: In static member function 'static T* node::Ob
jectWrap::Unwrap(v8::Local<v8::Object>) [with T = quad_tree::CollisionFilter]':
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h:35:3: warning: control reaches end of non-void
 function [-Wreturn-type]
   }
   ^
addon.target.mk:95: recipe for target 'Release/obj.target/addon/collision_filter.o' failed
make: *** [Release/obj.target/addon/collision_filter.o] Error 1
make: Leaving directory '/home/quadtree/QuadTree-node.js-addon-master/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "rebuild"
gyp ERR! cwd /home/quadtree/QuadTree-node.js-addon-master
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```
*****************************************************
**with electron-build.cmd:**
```
..........
In file included from ../collision_filter.h:4:0,
                 from ../collision_filter.cc:1:
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h: In instantiation of 'static T* node::ObjectWr
ap::Unwrap(v8::Local<v8::Object>) [with T = quad_tree::CollisionFilter]':
../collision_filter.cc:108:78:   required from here
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h:34:32: error: 'node::ObjectWrap' is an inacces
sible base of 'quad_tree::CollisionFilter'
     return static_cast<T*>(wrap);
                                ^
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h: In static member function 'static T* node::Ob
jectWrap::Unwrap(v8::Local<v8::Object>) [with T = quad_tree::CollisionFilter]':
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h:35:3: warning: control reaches end of non-void
 function [-Wreturn-type]
   }
   ^
addon.target.mk:95: recipe for target 'Release/obj.target/addon/collision_filter.o' failed
make: *** [Release/obj.target/addon/collision_filter.o] Error 1
make: Leaving directory '/home/quadtree/QuadTree-node.js-addon-master/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--target=1.4.13" "--arch=x64" "--dist-
url=https://atom.io/download/electron"
gyp ERR! cwd /home/quadtree/QuadTree-node.js-addon-master
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```
*********************************************
Thanks at advance!

**Comment by Surviver** [comment]
It seems the access permission of CollisionFilter's base class must be 'public', I have modified it and pushed just now. You can try to compile again. I just build successfully with vc on windows.

**Comment by Gimmo** [comment]
the same....................

In file included from ../collision_filter.h:4:0,
                 from ../collision_filter.cc:1:
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h: In instantiation of 'static T* node::ObjectWr
ap::Unwrap(v8::Local<v8::Object>) [with T = quad_tree::CollisionFilter]':
../collision_filter.cc:108:78:   required from here
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h:34:32: error: 'node::ObjectWrap' is an inacces
sible base of 'quad_tree::CollisionFilter'
     return static_cast<T*>(wrap);
                                ^
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h: In static member function 'static T* node::Ob
jectWrap::Unwrap(v8::Local<v8::Object>) [with T = quad_tree::CollisionFilter]':
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h:35:3: warning: control reaches end of non-void
 function [-Wreturn-type]
   }
   ^
addon.target.mk:95: recipe for target 'Release/obj.target/addon/collision_filter.o' failed
make: *** [Release/obj.target/addon/collision_filter.o] Error 1
make: Leaving directory '/home/quadtree/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure" "rebuild"
gyp ERR! cwd /home/quadtree
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

**Comment by Surviver** [comment]
I have built successfully under following environment:
- g++ 5.4.0
- node.js v6.9.4

**Comment by Gimmo** [comment]
- Debian 8
- g++ 5.4.1
- node.js v6.9.4

Error remains still

```
/root/.node-gyp/6.9.3/include/node/node_object_wrap.h:34:32: error: 'node::ObjectWrap' is an inacc
sible base of 'quad_tree::CollisionFilter'
     return static_cast<T*>(wrap);
```
Plus a lot of warnings appears
```

gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/addon/addon.o
  CXX(target) Release/obj.target/addon/rect.o
../rect.cc: In static member function 'static void quad_tree::Rect::New(const v8::FunctionCallback
fo<v8::Value>&)':
../rect.cc:98:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = info.GetIsolate();
            ^
../rect.cc: In static member function 'static void quad_tree::Rect::JS_SetFilter(const v8::Functio
allbackInfo<v8::Value>&)':
../rect.cc:235:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = args.GetIsolate();
            ^
In file included from /root/.node-gyp/6.9.3/include/node/node.h:42:0,
                 from ../rect.h:4,
                 from ../rect.cc:1:
/root/.node-gyp/6.9.3/include/node/v8.h: In static member function 'static void quad_tree::Rect::N
(const v8::FunctionCallbackInfo<v8::Value>&)':
/root/.node-gyp/6.9.3/include/node/v8.h:521:48: warning: 'js_rect' may be used uninitialized in th
 function [-Wmaybe-uninitialized]
   V8_INLINE bool IsEmpty() const { return val_ == NULL; }
                                                ^
../rect.cc:102:10: note: 'js_rect' was declared here
    Rect *js_rect;
          ^
  CXX(target) Release/obj.target/addon/quad_tree.o
../quad_tree.cc: In static member function 'static void quad_tree::QuadTree::New(const v8::Functio
allbackInfo<v8::Value>&)':
../quad_tree.cc:288:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = info.GetIsolate();
            ^
../quad_tree.cc: In static member function 'static void quad_tree::QuadTree::JS_AddObject(const v8
FunctionCallbackInfo<v8::Value>&)':
../quad_tree.cc:323:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = args.GetIsolate();
            ^
../quad_tree.cc: In static member function 'static void quad_tree::QuadTree::JS_AddObjects(const v
:FunctionCallbackInfo<v8::Value>&)':
../quad_tree.cc:332:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = args.GetIsolate();
            ^
../quad_tree.cc: In static member function 'static void quad_tree::QuadTree::JS_Clear(const v8::Fu
tionCallbackInfo<v8::Value>&)':
../quad_tree.cc:363:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = info.GetIsolate();
            ^
In file included from /root/.node-gyp/6.9.3/include/node/node.h:42:0,
                 from ../quad_tree.h:5,
                 from ../quad_tree.cc:1:
/root/.node-gyp/6.9.3/include/node/v8.h: In static member function 'static void quad_tree::QuadTre
:New(const v8::FunctionCallbackInfo<v8::Value>&)':
/root/.node-gyp/6.9.3/include/node/v8.h:521:48: warning: 'qtree' may be used uninitialized in this
unction [-Wmaybe-uninitialized]
   V8_INLINE bool IsEmpty() const { return val_ == NULL; }
                                                ^
../quad_tree.cc:292:14: note: 'qtree' was declared here
    QuadTree* qtree;
              ^
  CXX(target) Release/obj.target/addon/collision_filter.o
../collision_filter.cc: In static member function 'static void quad_tree::CollisionFilter::New(con
 v8::FunctionCallbackInfo<v8::Value>&)':
../collision_filter.cc:78:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = info.GetIsolate();
            ^
../collision_filter.cc: In static member function 'static void quad_tree::CollisionFilter::GroupSe
er(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)':
../collision_filter.cc:128:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = info.GetIsolate();
            ^
../collision_filter.cc: In static member function 'static void quad_tree::CollisionFilter::MaskSet
r(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)':
../collision_filter.cc:139:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = info.GetIsolate();
            ^
../collision_filter.cc: In static member function 'static void quad_tree::CollisionFilter::Categor
etter(v8::Local<v8::String>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&)':
../collision_filter.cc:150:12: warning: unused variable 'isolate' [-Wunused-variable]
   Isolate *isolate = info.GetIsolate();
            ^
```

**Comment by Gimmo** [comment]
Compiled without any problems.

- Debian 8
- g++ 5.4.1 
- node.js v6.9.4

Thanks.
